app:
  restriction:
    timeLimit:
      fromDate: '21:00:00'
      toDate: '07:00:00'
      enabled: true
    maxParticipation:
      value: 10
      enabled: true
    maxDocCreations:
      value: 5
      limitInMinutes: 60
      enabled: true
    maxParticipationBetweenCompanies:
      value: 2
      enabled: true
